/**
 * THE RECEIPT, AS A DOCUMENT — one HTML page shared by the web (printed
 * through the print portal) and the app (printed to a PDF on the phone).
 * Literal ink, millimetres, hairlines: it is paper in both themes.
 */
export interface FeeReceiptDoc {
  number: string;
  issuedAt: string;
  amountMinor: number;
  method: string;
  providerRef: string | null;
  paidOn: string;
  verifiedAt: string | null;
  termName: string | null;
  invoiceNumber: string | null;
  student: { name: string; admissionNo: string; className: string | null };
  school: { name: string };
}

const esc = (v: unknown) =>
  String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string);

const METHOD: Record<string, string> = {
  UPI: 'UPI', NEFT_IMPS: 'NEFT / IMPS', CHEQUE: 'Cheque', CASH: 'Cash at office', CARD: 'Card', NETBANKING: 'Net banking', OTHER: 'Other',
};

/** ₹24,500 — Indian grouping, paise only when there are any. */
export function receiptRupees(amountMinor: number): string {
  const abs = Math.abs(amountMinor);
  const whole = Math.floor(abs / 100);
  const paise = abs % 100;
  const s = String(whole);
  const grouped = s.length <= 3 ? s : `${s.slice(0, -3).replace(/\B(?=(\d{2})+(?!\d))/g, ',')},${s.slice(-3)}`;
  return `${amountMinor < 0 ? '−' : ''}₹${paise === 0 ? grouped : `${grouped}.${String(paise).padStart(2, '0')}`}`;
}

const day = (iso: string) =>
  new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Asia/Kolkata' });

/** The receipt's BODY markup — the web wraps it in its print portal, the app in a full document. */
export function receiptBody(r: FeeReceiptDoc): string {
  return `<div class="rcpt">
  <div class="rcpt-head"><h1>${esc(r.school.name)}</h1><div class="rcpt-kind">Fee receipt</div></div>
  <div class="rcpt-stamp">PAID</div>
  <div class="rcpt-amt">${esc(receiptRupees(r.amountMinor))}</div>
  <table class="rcpt-facts">
    <tr><th>Receipt no.</th><td>${esc(r.number)}</td></tr>
    <tr><th>Received from</th><td>${esc(r.student.name)}${r.student.className ? ` · ${esc(r.student.className)}` : ''} · Adm. ${esc(r.student.admissionNo)}</td></tr>
    ${r.termName ? `<tr><th>Towards</th><td>${esc(r.termName)}${r.invoiceNumber ? ` · ${esc(r.invoiceNumber)}` : ''}</td></tr>` : ''}
    <tr><th>Paid on</th><td>${esc(day(r.paidOn))} · ${esc(METHOD[r.method] ?? r.method)}${r.providerRef ? ` · ref ${esc(r.providerRef)}` : ''}</td></tr>
    <tr><th>Confirmed</th><td>${r.verifiedAt ? esc(day(r.verifiedAt)) : '—'}</td></tr>
  </table>
  <div class="rcpt-foot">Issued ${esc(day(r.issuedAt))} · Generated by Sckools — valid without a signature.</div>
</div>`;
}

/** The receipt's own CSS — the same rules on screen, in print, and in the phone's PDF. */
export const RECEIPT_CSS = `
.rcpt{font-family:Georgia,"Times New Roman",serif;color:#211D45;max-width:520px;margin:0 auto;padding:22px 24px;border:1px solid #d9d4c4;border-radius:6px;background:#fff;text-align:center}
.rcpt-head h1{font-size:20px;margin:0;font-weight:700}.rcpt-kind{font-family:Helvetica,Arial,sans-serif;font-size:10.5px;letter-spacing:.14em;text-transform:uppercase;color:#666;margin-top:3px}
.rcpt-stamp{display:inline-block;margin:16px auto 0;border:3px double #178A5B;color:#178A5B;font-weight:700;letter-spacing:.14em;font-size:22px;padding:6px 18px;border-radius:5px;transform:rotate(-6deg)}
.rcpt-amt{font-family:Menlo,Consolas,monospace;font-size:30px;font-weight:700;margin-top:14px;letter-spacing:-.01em}
.rcpt-facts{width:100%;border-collapse:collapse;margin-top:16px;font-size:12.5px;text-align:left}
.rcpt-facts th{font-family:Helvetica,Arial,sans-serif;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#666;font-weight:600;padding:7px 8px 7px 0;width:32%;vertical-align:top;border-top:1px solid #e5e5e5}
.rcpt-facts td{padding:7px 0;border-top:1px solid #e5e5e5}
.rcpt-foot{margin-top:16px;font-family:Helvetica,Arial,sans-serif;font-size:10px;color:#666}
@media print{.rcpt{border:0;padding:0}}
`;

/** A whole printable document — what the phone hands to expo-print. */
export function receiptHtml(r: FeeReceiptDoc): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>Receipt ${esc(r.number)}</title><style>@page{size:A5;margin:14mm}body{margin:0}${RECEIPT_CSS}</style></head><body>${receiptBody(r)}</body></html>`;
}
