import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    WEB_PORT: z.ZodDefault<z.ZodNumber>;
    WORKER_PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodUnion<[z.ZodString, z.ZodString]>;
    DATABASE_URL_APP: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    DATABASE_URL_PLATFORM: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodString]>>;
    DATABASE_URL_TEST: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodUnion<[z.ZodString, z.ZodString]>;
    S3_ENDPOINT: z.ZodString;
    S3_ACCESS_KEY: z.ZodString;
    S3_SECRET_KEY: z.ZodString;
    S3_BUCKET: z.ZodString;
    S3_REGION: z.ZodDefault<z.ZodString>;
    S3_FORCE_PATH_STYLE: z.ZodEffects<z.ZodDefault<z.ZodString>, boolean, string | undefined>;
    S3_PUBLIC_URL_BASE: z.ZodOptional<z.ZodString>;
    SMTP_HOST: z.ZodString;
    SMTP_PORT: z.ZodNumber;
    SMTP_FROM: z.ZodString;
    SMTP_USER: z.ZodOptional<z.ZodString>;
    SMTP_PASS: z.ZodOptional<z.ZodString>;
    OWNER_GATE_PASSWORD: z.ZodOptional<z.ZodString>;
    JWT_SCHOOL_ACCESS_SECRET: z.ZodString;
    JWT_SCHOOL_REFRESH_SECRET: z.ZodString;
    JWT_PLATFORM_ACCESS_SECRET: z.ZodString;
    JWT_PLATFORM_REFRESH_SECRET: z.ZodString;
    JWT_ACCESS_TTL: z.ZodDefault<z.ZodNumber>;
    JWT_REFRESH_TTL: z.ZodDefault<z.ZodNumber>;
    LOCKOUT_MAX_ATTEMPTS: z.ZodDefault<z.ZodNumber>;
    LOCKOUT_DURATION_SECONDS: z.ZodDefault<z.ZodNumber>;
    PLATFORM_HOST: z.ZodDefault<z.ZodString>;
    PLATFORM_OWNER_HOST: z.ZodDefault<z.ZodString>;
    PLATFORM_IP_ALLOWLIST: z.ZodEffects<z.ZodDefault<z.ZodString>, string[], string | undefined>;
    INGRESS_CNAME_TARGET: z.ZodDefault<z.ZodString>;
    INGRESS_A_RECORD: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    API_PORT: number;
    WEB_PORT: number;
    WORKER_PORT: number;
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET: string;
    S3_REGION: string;
    S3_FORCE_PATH_STYLE: boolean;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_FROM: string;
    JWT_SCHOOL_ACCESS_SECRET: string;
    JWT_SCHOOL_REFRESH_SECRET: string;
    JWT_PLATFORM_ACCESS_SECRET: string;
    JWT_PLATFORM_REFRESH_SECRET: string;
    JWT_ACCESS_TTL: number;
    JWT_REFRESH_TTL: number;
    LOCKOUT_MAX_ATTEMPTS: number;
    LOCKOUT_DURATION_SECONDS: number;
    PLATFORM_HOST: string;
    PLATFORM_OWNER_HOST: string;
    PLATFORM_IP_ALLOWLIST: string[];
    INGRESS_CNAME_TARGET: string;
    INGRESS_A_RECORD: string;
    DATABASE_URL_APP?: string | undefined;
    DATABASE_URL_PLATFORM?: string | undefined;
    DATABASE_URL_TEST?: string | undefined;
    S3_PUBLIC_URL_BASE?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    OWNER_GATE_PASSWORD?: string | undefined;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_FROM: string;
    JWT_SCHOOL_ACCESS_SECRET: string;
    JWT_SCHOOL_REFRESH_SECRET: string;
    JWT_PLATFORM_ACCESS_SECRET: string;
    JWT_PLATFORM_REFRESH_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    API_PORT?: number | undefined;
    WEB_PORT?: number | undefined;
    WORKER_PORT?: number | undefined;
    DATABASE_URL_APP?: string | undefined;
    DATABASE_URL_PLATFORM?: string | undefined;
    DATABASE_URL_TEST?: string | undefined;
    S3_REGION?: string | undefined;
    S3_FORCE_PATH_STYLE?: string | undefined;
    S3_PUBLIC_URL_BASE?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    OWNER_GATE_PASSWORD?: string | undefined;
    JWT_ACCESS_TTL?: number | undefined;
    JWT_REFRESH_TTL?: number | undefined;
    LOCKOUT_MAX_ATTEMPTS?: number | undefined;
    LOCKOUT_DURATION_SECONDS?: number | undefined;
    PLATFORM_HOST?: string | undefined;
    PLATFORM_OWNER_HOST?: string | undefined;
    PLATFORM_IP_ALLOWLIST?: string | undefined;
    INGRESS_CNAME_TARGET?: string | undefined;
    INGRESS_A_RECORD?: string | undefined;
}>;
export type AppEnv = z.infer<typeof envSchema>;
export declare function loadEnv(source?: NodeJS.ProcessEnv): AppEnv;
export {};
//# sourceMappingURL=index.d.ts.map