ALTER TABLE "SchoolProfile" ADD COLUMN "headingFont" TEXT NOT NULL DEFAULT 'INTER';
ALTER TABLE "SchoolProfile" ADD COLUMN "heroStyle" TEXT NOT NULL DEFAULT 'ILLUSTRATION';
ALTER TABLE "SchoolProfile" ADD COLUMN "animationLevel" TEXT NOT NULL DEFAULT 'FULL';
ALTER TABLE "SchoolProfile" ADD COLUMN "themePreset" TEXT;
