import { Prisma } from '@skoolos/db';
import type { UpdateProfileDto, UpdateHomepageDto, StatItemDto, SocialLinkDto } from './cms.dto';
export declare class SiteContentService {
    getContent(schoolId: string): Promise<{
        profile: {
            email: string | null;
            id: string;
            schoolId: string;
            region: string | null;
            phone: string | null;
            logoAssetId: string | null;
            faviconAssetId: string | null;
            brandColorPrimary: string;
            brandColorSecondary: string;
            headingFont: string;
            heroStyle: string;
            animationLevel: string;
            themePreset: string | null;
            heroLayout: string;
            heroTextAlign: string;
            heroOverlayStyle: string;
            heroOverlayOpacity: number;
            heroHeight: string;
            headlineAccent: string;
            sectionShape: string;
            motionGesture: string;
            backgroundTexture: string;
            navConfig: Prisma.JsonValue | null;
            navStyle: string;
            navColor: string;
            navTextColor: string;
            navCtaLabel: string;
            navShowCta: boolean;
            navShowLogin: boolean;
            navLoginLabel: string;
            navLoginStyle: string;
            blogLayout: string;
            blogHeroLimit: number;
            addressLine1: string | null;
            addressLine2: string | null;
            city: string | null;
            postalCode: string | null;
            country: string | null;
            geoLat: number | null;
            geoLng: number | null;
            mapEmbedUrl: string | null;
        } | null;
        homepage: {
            id: string;
            schoolId: string;
            heroAssetId: string | null;
            headline: string;
            subheadline: string | null;
            aboutText: string | null;
            principalName: string | null;
            principalMessage: string | null;
            principalPhotoAssetId: string | null;
            aboutImageAssetId: string | null;
            heroImageAssetIds: string[];
            showAdmissions: boolean;
            showGallery: boolean;
            showEvents: boolean;
            showContact: boolean;
        } | null;
        stats: {
            value: string;
            id: string;
            schoolId: string;
            order: number;
            label: string;
        }[];
        socialLinks: {
            platform: import("@skoolos/db").$Enums.SocialPlatform;
            id: string;
            schoolId: string;
            url: string;
            order: number;
        }[];
    }>;
    updateProfile(schoolId: string, dto: UpdateProfileDto): Promise<{
        profile: {
            email: string | null;
            id: string;
            schoolId: string;
            region: string | null;
            phone: string | null;
            logoAssetId: string | null;
            faviconAssetId: string | null;
            brandColorPrimary: string;
            brandColorSecondary: string;
            headingFont: string;
            heroStyle: string;
            animationLevel: string;
            themePreset: string | null;
            heroLayout: string;
            heroTextAlign: string;
            heroOverlayStyle: string;
            heroOverlayOpacity: number;
            heroHeight: string;
            headlineAccent: string;
            sectionShape: string;
            motionGesture: string;
            backgroundTexture: string;
            navConfig: Prisma.JsonValue | null;
            navStyle: string;
            navColor: string;
            navTextColor: string;
            navCtaLabel: string;
            navShowCta: boolean;
            navShowLogin: boolean;
            navLoginLabel: string;
            navLoginStyle: string;
            blogLayout: string;
            blogHeroLimit: number;
            addressLine1: string | null;
            addressLine2: string | null;
            city: string | null;
            postalCode: string | null;
            country: string | null;
            geoLat: number | null;
            geoLng: number | null;
            mapEmbedUrl: string | null;
        } | null;
        homepage: {
            id: string;
            schoolId: string;
            heroAssetId: string | null;
            headline: string;
            subheadline: string | null;
            aboutText: string | null;
            principalName: string | null;
            principalMessage: string | null;
            principalPhotoAssetId: string | null;
            aboutImageAssetId: string | null;
            heroImageAssetIds: string[];
            showAdmissions: boolean;
            showGallery: boolean;
            showEvents: boolean;
            showContact: boolean;
        } | null;
        stats: {
            value: string;
            id: string;
            schoolId: string;
            order: number;
            label: string;
        }[];
        socialLinks: {
            platform: import("@skoolos/db").$Enums.SocialPlatform;
            id: string;
            schoolId: string;
            url: string;
            order: number;
        }[];
    }>;
    updateHomepage(schoolId: string, dto: UpdateHomepageDto): Promise<{
        profile: {
            email: string | null;
            id: string;
            schoolId: string;
            region: string | null;
            phone: string | null;
            logoAssetId: string | null;
            faviconAssetId: string | null;
            brandColorPrimary: string;
            brandColorSecondary: string;
            headingFont: string;
            heroStyle: string;
            animationLevel: string;
            themePreset: string | null;
            heroLayout: string;
            heroTextAlign: string;
            heroOverlayStyle: string;
            heroOverlayOpacity: number;
            heroHeight: string;
            headlineAccent: string;
            sectionShape: string;
            motionGesture: string;
            backgroundTexture: string;
            navConfig: Prisma.JsonValue | null;
            navStyle: string;
            navColor: string;
            navTextColor: string;
            navCtaLabel: string;
            navShowCta: boolean;
            navShowLogin: boolean;
            navLoginLabel: string;
            navLoginStyle: string;
            blogLayout: string;
            blogHeroLimit: number;
            addressLine1: string | null;
            addressLine2: string | null;
            city: string | null;
            postalCode: string | null;
            country: string | null;
            geoLat: number | null;
            geoLng: number | null;
            mapEmbedUrl: string | null;
        } | null;
        homepage: {
            id: string;
            schoolId: string;
            heroAssetId: string | null;
            headline: string;
            subheadline: string | null;
            aboutText: string | null;
            principalName: string | null;
            principalMessage: string | null;
            principalPhotoAssetId: string | null;
            aboutImageAssetId: string | null;
            heroImageAssetIds: string[];
            showAdmissions: boolean;
            showGallery: boolean;
            showEvents: boolean;
            showContact: boolean;
        } | null;
        stats: {
            value: string;
            id: string;
            schoolId: string;
            order: number;
            label: string;
        }[];
        socialLinks: {
            platform: import("@skoolos/db").$Enums.SocialPlatform;
            id: string;
            schoolId: string;
            url: string;
            order: number;
        }[];
    }>;
    setStats(schoolId: string, items: StatItemDto[]): Promise<{
        profile: {
            email: string | null;
            id: string;
            schoolId: string;
            region: string | null;
            phone: string | null;
            logoAssetId: string | null;
            faviconAssetId: string | null;
            brandColorPrimary: string;
            brandColorSecondary: string;
            headingFont: string;
            heroStyle: string;
            animationLevel: string;
            themePreset: string | null;
            heroLayout: string;
            heroTextAlign: string;
            heroOverlayStyle: string;
            heroOverlayOpacity: number;
            heroHeight: string;
            headlineAccent: string;
            sectionShape: string;
            motionGesture: string;
            backgroundTexture: string;
            navConfig: Prisma.JsonValue | null;
            navStyle: string;
            navColor: string;
            navTextColor: string;
            navCtaLabel: string;
            navShowCta: boolean;
            navShowLogin: boolean;
            navLoginLabel: string;
            navLoginStyle: string;
            blogLayout: string;
            blogHeroLimit: number;
            addressLine1: string | null;
            addressLine2: string | null;
            city: string | null;
            postalCode: string | null;
            country: string | null;
            geoLat: number | null;
            geoLng: number | null;
            mapEmbedUrl: string | null;
        } | null;
        homepage: {
            id: string;
            schoolId: string;
            heroAssetId: string | null;
            headline: string;
            subheadline: string | null;
            aboutText: string | null;
            principalName: string | null;
            principalMessage: string | null;
            principalPhotoAssetId: string | null;
            aboutImageAssetId: string | null;
            heroImageAssetIds: string[];
            showAdmissions: boolean;
            showGallery: boolean;
            showEvents: boolean;
            showContact: boolean;
        } | null;
        stats: {
            value: string;
            id: string;
            schoolId: string;
            order: number;
            label: string;
        }[];
        socialLinks: {
            platform: import("@skoolos/db").$Enums.SocialPlatform;
            id: string;
            schoolId: string;
            url: string;
            order: number;
        }[];
    }>;
    setSocial(schoolId: string, links: SocialLinkDto[]): Promise<{
        profile: {
            email: string | null;
            id: string;
            schoolId: string;
            region: string | null;
            phone: string | null;
            logoAssetId: string | null;
            faviconAssetId: string | null;
            brandColorPrimary: string;
            brandColorSecondary: string;
            headingFont: string;
            heroStyle: string;
            animationLevel: string;
            themePreset: string | null;
            heroLayout: string;
            heroTextAlign: string;
            heroOverlayStyle: string;
            heroOverlayOpacity: number;
            heroHeight: string;
            headlineAccent: string;
            sectionShape: string;
            motionGesture: string;
            backgroundTexture: string;
            navConfig: Prisma.JsonValue | null;
            navStyle: string;
            navColor: string;
            navTextColor: string;
            navCtaLabel: string;
            navShowCta: boolean;
            navShowLogin: boolean;
            navLoginLabel: string;
            navLoginStyle: string;
            blogLayout: string;
            blogHeroLimit: number;
            addressLine1: string | null;
            addressLine2: string | null;
            city: string | null;
            postalCode: string | null;
            country: string | null;
            geoLat: number | null;
            geoLng: number | null;
            mapEmbedUrl: string | null;
        } | null;
        homepage: {
            id: string;
            schoolId: string;
            heroAssetId: string | null;
            headline: string;
            subheadline: string | null;
            aboutText: string | null;
            principalName: string | null;
            principalMessage: string | null;
            principalPhotoAssetId: string | null;
            aboutImageAssetId: string | null;
            heroImageAssetIds: string[];
            showAdmissions: boolean;
            showGallery: boolean;
            showEvents: boolean;
            showContact: boolean;
        } | null;
        stats: {
            value: string;
            id: string;
            schoolId: string;
            order: number;
            label: string;
        }[];
        socialLinks: {
            platform: import("@skoolos/db").$Enums.SocialPlatform;
            id: string;
            schoolId: string;
            url: string;
            order: number;
        }[];
    }>;
}
//# sourceMappingURL=site-content.service.d.ts.map