import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';

interface MarkRow {
  subject: string;
  obtained: number;
  max: number;
  isAbsent: boolean;
}

interface ReportCardInput {
  schoolName: string;
  student: { firstName: string; lastName: string; email: string };
  examName: string;
  className: string;
  publishedAt: Date;
  marks: MarkRow[];
  bands: Array<{ min: number; letter: string }> | null;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, color: '#0f172a' },
  header: { marginBottom: 16, borderBottom: '1pt solid #e2e8f0', paddingBottom: 12 },
  school: { fontSize: 18, fontWeight: 'bold' },
  examLine: { marginTop: 4, color: '#64748b' },
  studentBlock: { marginBottom: 16 },
  label: { color: '#64748b', fontSize: 10 },
  value: { fontSize: 12, fontWeight: 'bold' },
  table: { marginTop: 8, border: '1pt solid #e2e8f0', borderRadius: 4 },
  tr: { flexDirection: 'row', borderBottom: '1pt solid #f1f5f9' },
  trLast: { flexDirection: 'row' },
  th: { padding: 8, fontWeight: 'bold', backgroundColor: '#f8fafc', fontSize: 10 },
  td: { padding: 8, fontSize: 11 },
  c1: { flex: 3 },
  c2: { flex: 1, textAlign: 'right' },
  c3: { flex: 1, textAlign: 'right' },
  c4: { flex: 1, textAlign: 'center' },
  totalRow: { flexDirection: 'row', marginTop: 16, padding: 8, backgroundColor: '#0f172a', borderRadius: 4 },
  totalText: { color: 'white', fontWeight: 'bold' },
  footer: { marginTop: 32, fontSize: 9, color: '#94a3b8', textAlign: 'center' },
});

function letterFor(pct: number, bands: ReportCardInput['bands']): string {
  if (!bands) return '—';
  // Bands are stored sorted desc on min — first match wins.
  const sorted = [...bands].sort((a, b) => b.min - a.min);
  const hit = sorted.find((b) => pct >= b.min);
  return hit?.letter ?? '—';
}

function ReportCardDoc({ data }: { data: ReportCardInput }) {
  const total = data.marks.reduce((s, m) => s + (m.isAbsent ? 0 : m.obtained), 0);
  const max = data.marks.reduce((s, m) => s + m.max, 0);
  const pct = max > 0 ? (total / max) * 100 : 0;
  const overallLetter = letterFor(pct, data.bands);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.school}>{data.schoolName}</Text>
          <Text style={styles.examLine}>
            Report Card · {data.examName} · {data.className}
          </Text>
        </View>

        <View style={styles.studentBlock}>
          <Text style={styles.label}>Student</Text>
          <Text style={styles.value}>
            {data.student.firstName} {data.student.lastName}
          </Text>
          <Text style={styles.label}>{data.student.email}</Text>
          <Text style={styles.label}>Published {data.publishedAt.toISOString().slice(0, 10)}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tr}>
            <Text style={[styles.th, styles.c1]}>Subject</Text>
            <Text style={[styles.th, styles.c2]}>Obtained</Text>
            <Text style={[styles.th, styles.c3]}>Max</Text>
            <Text style={[styles.th, styles.c4]}>Grade</Text>
          </View>
          {data.marks.map((m, i) => {
            const subjPct = m.isAbsent ? 0 : (m.obtained / m.max) * 100;
            const last = i === data.marks.length - 1;
            return (
              <View key={i} style={last ? styles.trLast : styles.tr}>
                <Text style={[styles.td, styles.c1]}>{m.subject}</Text>
                <Text style={[styles.td, styles.c2]}>{m.isAbsent ? 'AB' : m.obtained.toFixed(2)}</Text>
                <Text style={[styles.td, styles.c3]}>{m.max}</Text>
                <Text style={[styles.td, styles.c4]}>{m.isAbsent ? 'AB' : letterFor(subjPct, data.bands)}</Text>
              </View>
            );
          })}
        </View>

        <View style={styles.totalRow}>
          <Text style={[styles.totalText, styles.c1]}>Overall</Text>
          <Text style={[styles.totalText, styles.c2]}>{total.toFixed(2)}</Text>
          <Text style={[styles.totalText, styles.c3]}>{max}</Text>
          <Text style={[styles.totalText, styles.c4]}>
            {overallLetter} ({pct.toFixed(1)}%)
          </Text>
        </View>

        <Text style={styles.footer}>Generated by SkoolOS · {new Date().toISOString()}</Text>
      </Page>
    </Document>
  );
}

export async function renderReportCardPdf(data: ReportCardInput): Promise<Buffer> {
  return renderToBuffer(<ReportCardDoc data={data} />);
}
