/**
 * Which routes have had their authorization looked at.
 *
 * Read `route-coverage.e2e-spec.ts` for why this file exists. In short: a
 * controller shipped with a guard on two of its six handlers and a STUDENT
 * token could delete staff records, and no test noticed for months. This
 * manifest makes "nobody has looked at this route" a failing test rather than
 * a silent state.
 *
 * It is NOT a claim that a route is correctly guarded — no static list can be.
 * It is a claim that a human decided who may call it and wrote an assertion.
 */

/**
 * Routes whose authorization has been decided AND asserted in a test.
 *
 * Add a route here only once there is an assertion covering it — otherwise
 * this becomes a list of good intentions.
 */
export const AUTHZ_REVIEWED: string[] = [
  "DELETE /manage/announcements/:id",
  "DELETE /manage/assignments/:id",
  "DELETE /manage/classes/:id",
  "DELETE /manage/staff/:id",
  "DELETE /manage/timetable/:id",
  "GET /internal/cron/notification-outbox",
  "GET /manage/announcements/mine",
  "GET /manage/assignments",
  "GET /manage/classes",
  "GET /manage/library/day",
  "GET /manage/library/members",
  "GET /manage/library/next-numbers",
  "GET /manage/library/not-returned",
  "GET /manage/library/period/now",
  "GET /manage/library/status",
  "GET /manage/staff",
  "GET /manage/staff-attendance",
  "GET /manage/staff-attendance/mine",
  "GET /manage/timetable",
  "GET /manage/timetable/my-day",
  "GET /me/assignments",
  "GET /me/library",
  "PATCH /manage/announcements/:id",
  "POST /internal/cron/notification-outbox",
  "POST /manage/assignments",
  "POST /manage/assignments/upload",
  "POST /manage/classes",
  "POST /manage/library/books",
  "POST /manage/library/damage",
  "POST /manage/library/enrol",
  "POST /manage/library/issue",
  "POST /manage/library/nudge",
  "POST /manage/library/period/present",
  "POST /manage/library/renew",
  "POST /manage/library/return",
  "POST /manage/library/undo",
  "POST /manage/staff",
  "POST /manage/staff/:id/invite/resend",
  "POST /manage/staff/:id/login",
  "POST /manage/timetable",
  "POST /me/assignments/:id/seen",
  "PUT /manage/classes/:id",
  "PUT /manage/staff-attendance",
  "PUT /manage/staff/:id",
];

/**
 * Everything that predates this guard.
 *
 * MAY ONLY SHRINK. A new route belongs in `AUTHZ_REVIEWED`; putting one here
 * would defeat the entire point, which is that new code cannot slip through
 * unexamined. Moving a route out of this list means: decide who may call it,
 * write the assertion, move the string.
 */
export const AUTHZ_UNREVIEWED: string[] = [
  "DELETE /cms/blog/posts/:id",
  "DELETE /cms/blog/selections/:postId",
  "DELETE /manage/class-notes/:id",
  "DELETE /manage/class-todos/:id",
  "DELETE /manage/diary/:id",
  "DELETE /manage/events/:id",
  "DELETE /manage/grades/:id",
  "DELETE /manage/holidays/:id",
  "DELETE /manage/periods/:id",
  "DELETE /manage/students/:id",
  "DELETE /manage/subjects/:id",
  "DELETE /manage/teachers/:id",
  "DELETE /owner/schools/:id",
  "DELETE /site/courses/:id",
  "DELETE /site/media/:id",
  "DELETE /site/staff/:id",
  "GET /auth/me",
  "GET /cms/blog/library",
  "GET /cms/blog/posts",
  "GET /cms/blog/posts/:id",
  "GET /cms/blog/selections",
  "GET /cms/blog/settings",
  "GET /directory",
  "GET /health",
  "GET /internal/cron/exam-reminders",
  "GET /manage/announcements",
  "GET /manage/attendance",
  "GET /manage/attendance/my-classes",
  "GET /manage/attendance/rates",
  "GET /manage/attendance/status",
  "GET /manage/availability",
  "GET /manage/class-log",
  "GET /manage/class-notes",
  "GET /manage/diary",
  "GET /manage/events",
  "GET /manage/events/:id/registrations",
  "GET /manage/exams",
  "GET /manage/exams/:id/results",
  "GET /manage/grades",
  "GET /manage/holidays",
  "GET /manage/jobs",
  "GET /manage/jobs/:id/applications",
  "GET /manage/leave",
  "GET /manage/leave-policy/allocations",
  "GET /manage/leave-policy/my-balance",
  "GET /manage/leave-policy/pending-context",
  "GET /manage/leave-policy/types",
  "GET /manage/leave/coverage",
  "GET /manage/leave/mine",
  "GET /manage/library/copies/:accessionNumber",
  "GET /manage/messages",
  "GET /manage/messages/:threadId",
  "GET /manage/messages/unread-count",
  "GET /manage/note-classes",
  "GET /manage/periods",
  "GET /manage/register-changes",
  "GET /manage/register-changes/mine",
  "GET /manage/requests/pending-count",
  "GET /manage/school/class-note-visibility",
  "GET /manage/school/working-days",
  "GET /manage/staff-attendance/person",
  "GET /manage/students",
  "GET /manage/subjects",
  "GET /manage/teachers",
  "GET /manage/teachers/me",
  "GET /manage/timetable/mine",
  "GET /manage/years",
  "GET /marketing/blog",
  "GET /marketing/blog/:globalSlug",
  "GET /marketing/config",
  "GET /me/announcements",
  "GET /me/attendance",
  "GET /me/diary",
  "GET /me/exams",
  "GET /me/holidays",
  "GET /me/library/class",
  "GET /me/library/shelf",
  "GET /me/messages",
  "GET /me/messages/:threadId",
  "GET /me/messages/teachers",
  "GET /me/messages/unread-count",
  "GET /me/notifications",
  "GET /me/notifications/unread-count",
  "GET /me/profile",
  "GET /me/results",
  "GET /me/timetable",
  "GET /owner/blog/pending",
  "GET /owner/events",
  "GET /owner/jobs",
  "GET /owner/leads",
  "GET /owner/marketing-config",
  "GET /owner/overview",
  "GET /owner/schools",
  "GET /owner/schools/:id",
  "GET /owner/schools/:id/admins",
  "GET /owner/schools/:id/enquiries.csv",
  "GET /owner/stats",
  "GET /public/blog",
  "GET /public/blog/:slug",
  "GET /public/jobs",
  "GET /public/jobs/:id",
  "GET /public/site",
  "GET /ready",
  "GET /site/admissions",
  "GET /site/content",
  "GET /site/courses",
  "GET /site/enquiries",
  "GET /site/hall-of-fame",
  "GET /site/media",
  "GET /site/staff",
  "GET /students",
  "GET /students/:id",
  "GET /teachers/:id",
  "GET /users",
  "GET /users/:id",
  "PATCH /cms/blog/posts/:id",
  "PATCH /cms/blog/selections/:postId",
  "PATCH /cms/blog/settings",
  "PATCH /manage/class-todos/:id",
  "PATCH /manage/diary/:id",
  "PATCH /manage/events/:id",
  "PATCH /manage/events/registrations/:registrationId",
  "PATCH /manage/jobs/:id",
  "PATCH /manage/jobs/applications/:id",
  "PATCH /manage/leave-policy/types/:id",
  "PATCH /owner/events/:id",
  "PATCH /owner/jobs/:id",
  "PATCH /owner/leads/:id",
  "PATCH /owner/schools/:id/features",
  "PATCH /owner/schools/:id/status",
  "PATCH /owner/schools/:id/tier",
  "PATCH /site/enquiries/:id",
  "POST /auth/accept-invite",
  "POST /auth/change-password",
  "POST /auth/forgot-password",
  "POST /auth/impersonate",
  "POST /auth/login",
  "POST /auth/logout",
  "POST /auth/refresh",
  "POST /auth/reset-by-code",
  "POST /auth/reset-password",
  "POST /auth/resolve-school",
  "POST /cms/blog/posts",
  "POST /cms/blog/posts/:id/publish",
  "POST /cms/blog/posts/:id/submit-global",
  "POST /cms/blog/selections",
  "POST /internal/cron/exam-reminders",
  "POST /manage/announcements",
  "POST /manage/attendance/notify-low",
  "POST /manage/class-notes",
  "POST /manage/class-todos",
  "POST /manage/diary",
  "POST /manage/events",
  "POST /manage/events/:id/registrations",
  "POST /manage/exams",
  "POST /manage/exams/:id/publish",
  "POST /manage/grades",
  "POST /manage/holidays",
  "POST /manage/jobs",
  "POST /manage/jobs/:id/close",
  "POST /manage/jobs/:id/submit",
  "POST /manage/leave",
  "POST /manage/leave-policy/allocations/apply-defaults",
  "POST /manage/leave-policy/close-year",
  "POST /manage/leave-policy/types",
  "POST /manage/leave/:id/approve",
  "POST /manage/leave/:id/cancel",
  "POST /manage/leave/:id/reject",
  "POST /manage/messages/:threadId",
  "POST /manage/periods",
  "POST /manage/register-changes",
  "POST /manage/register-changes/:id/approve",
  "POST /manage/register-changes/:id/reject",
  "POST /manage/students",
  "POST /manage/students/:id/invite/resend",
  "POST /manage/students/:id/login",
  "POST /manage/subjects",
  "POST /manage/substitution/:id/assign",
  "POST /manage/substitution/:id/clear",
  "POST /manage/teachers",
  "POST /manage/teachers/:id/invite/resend",
  "POST /manage/teachers/:id/login",
  "POST /manage/teachers/:id/release",
  "POST /manage/years",
  "POST /marketing/leads",
  "POST /me/diary/:id/sign",
  "POST /me/events/:id/register",
  "POST /me/messages",
  "POST /me/notifications/clear",
  "POST /me/notifications/read",
  "POST /me/photo",
  "POST /me/push-token",
  "POST /owner/auth/gate",
  "POST /owner/auth/login",
  "POST /owner/auth/refresh",
  "POST /owner/blog/:id/approve",
  "POST /owner/blog/:id/reject",
  "POST /owner/events",
  "POST /owner/schools",
  "POST /owner/schools/:id/admins/:userId/reset-password",
  "POST /owner/schools/:id/impersonate",
  "POST /public/enquiry",
  "POST /public/events/:id/register",
  "POST /public/jobs/:id/apply",
  "POST /site/courses",
  "POST /site/media",
  "POST /site/staff",
  "PUT /manage/attendance",
  "PUT /manage/exams/:id/results",
  "PUT /manage/grades/:id",
  "PUT /manage/leave-policy/allocations",
  "PUT /manage/periods/:id",
  "PUT /manage/school/class-note-visibility",
  "PUT /manage/school/working-days",
  "PUT /manage/students/:id",
  "PUT /manage/subjects/:id",
  "PUT /manage/teachers/:id",
  "PUT /owner/marketing-config",
  "PUT /site/admissions/settings",
  "PUT /site/admissions/steps",
  "PUT /site/courses/:id",
  "PUT /site/courses/:id/fee",
  "PUT /site/hall-of-fame/:courseId",
  "PUT /site/homepage",
  "PUT /site/profile",
  "PUT /site/social",
  "PUT /site/staff/:id",
  "PUT /site/stats",
];
